/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package is2trabajopatrones.GUI;

import is2trabajopatrones.IS2TrabajoPatrones;
import TiendaProducto.Producto;
import TiendaProducto.Tienda;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;

/**
 *
 * @author Equipo
 */
public class ClienteFranquiciado_GUI extends javax.swing.JFrame {

    /**
     * Creates new form ClienteFranquiciado_GUI
     */
    DefaultListModel productos = new DefaultListModel();
    public ClienteFranquiciado_GUI() {
        initComponents();
        jList1.setModel(productos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Encabezado = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BotonVolver = new javax.swing.JButton();
        BotonComprar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        LabelNombre = new javax.swing.JLabel();
        LabelDNI = new javax.swing.JLabel();
        LabelEDAD = new javax.swing.JLabel();
        LabelIdCuenta = new javax.swing.JLabel();
        LabelSaldo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LabelNombreTienda = new javax.swing.JLabel();
        LabelLocalizacion = new javax.swing.JLabel();
        LabelIdTienda = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BotonActualizaLista = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        BotonAñadirProducto = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TextoNombreProducto = new javax.swing.JTextField();
        TextoPrecioProducto = new javax.swing.JTextField();
        BotonEliminarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Encabezado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Encabezado.setText("PRUEBA");

        jLabel2.setText("Sus datos son:");

        jLabel1.setText("Nombre:");

        jLabel3.setText("DNI:");

        jLabel4.setText("Edad:");

        jLabel5.setText("ID de cuenta:");

        jLabel6.setText("SALDO:");

        BotonVolver.setText("Cerrar sesion");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        BotonComprar.setText("Comprar");
        BotonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComprarActionPerformed(evt);
            }
        });

        jLabel7.setText("Cuenta Cliente Franquiciado con Tienda asociada");

        LabelNombre.setText("---");

        LabelDNI.setText("---");

        LabelEDAD.setText("---");

        LabelIdCuenta.setText("---");

        LabelSaldo.setText("---");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel8.setText("Nombre:");

        jLabel9.setText("Localizacion:");

        jLabel10.setText("ID de tienda:");

        LabelNombreTienda.setText("---");

        LabelLocalizacion.setText("---");

        LabelIdTienda.setText("---");

        jLabel11.setText("Productos---------->");

        BotonActualizaLista.setText("Actualizar lista");
        BotonActualizaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizaListaActionPerformed(evt);
            }
        });

        BotonAñadirProducto.setText("Añadir producto");
        BotonAñadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirProductoActionPerformed(evt);
            }
        });

        jLabel12.setText("Nombre:");

        jLabel13.setText("Precio");

        BotonEliminarProducto.setText("Eliminar producto");
        BotonEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonVolver)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelSaldo))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelIdCuenta))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelEDAD))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelDNI))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelNombre))))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 240, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LabelIdTienda)
                                                .addGap(15, 15, 15))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(LabelNombreTienda))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(LabelLocalizacion)))))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BotonComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2)
                                    .addComponent(BotonActualizaLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotonAñadirProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextoPrecioProducto)
                                            .addComponent(TextoNombreProducto))
                                        .addGap(17, 17, 17))
                                    .addComponent(BotonEliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Encabezado)
                .addGap(267, 267, 267))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Encabezado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(LabelNombre)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(LabelDNI)
                            .addComponent(jLabel8)
                            .addComponent(LabelNombreTienda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(LabelEDAD)
                            .addComponent(jLabel9)
                            .addComponent(LabelLocalizacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(LabelIdCuenta)
                            .addComponent(jLabel10)
                            .addComponent(LabelIdTienda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(LabelSaldo)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonActualizaLista)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(TextoNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TextoPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonVolver))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(BotonAñadirProducto)
                        .addGap(18, 18, 18)
                        .addComponent(BotonEliminarProducto)
                        .addContainerGap(18, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComprarActionPerformed
        IS2TrabajoPatrones.compra.setVisible(true);
        IS2TrabajoPatrones.compra.tiendas.removeAllElements();
        for(Tienda t : IS2TrabajoPatrones.trabajo.getListaDeTiendas()){
            IS2TrabajoPatrones.compra.tiendas.addElement(t);
        }
        IS2TrabajoPatrones.compra.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_BotonComprarActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        IS2TrabajoPatrones.pantIni.setVisible(true);
        IS2TrabajoPatrones.pantIni.setLocationRelativeTo(null);
        IS2TrabajoPatrones.sesionActual = null;
        this.setVisible(false);
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void BotonActualizaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizaListaActionPerformed
        productos.removeAllElements();
        Tienda t = IS2TrabajoPatrones.trabajo.BuscarTienda(LabelIdTienda.getText());
        for(Producto p:t.getLdp()){
            productos.addElement(p);
        }
    }//GEN-LAST:event_BotonActualizaListaActionPerformed

    private void BotonAñadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirProductoActionPerformed
        Tienda t = IS2TrabajoPatrones.trabajo.BuscarTienda(LabelIdTienda.getText());
        t.creaProducto(TextoNombreProducto.getText(), (double)Double.parseDouble(TextoPrecioProducto.getText()));
    }//GEN-LAST:event_BotonAñadirProductoActionPerformed

    private void BotonEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarProductoActionPerformed
        Tienda t = IS2TrabajoPatrones.trabajo.BuscarTienda(LabelIdTienda.getText());
        int index = jList1.getSelectedIndex();
        Producto p = (Producto)productos.getElementAt(index);
        t.removeProducto(p);
    }//GEN-LAST:event_BotonEliminarProductoActionPerformed

    public JLabel getEncabezado() {
        return Encabezado;
    }

    public void setEncabezado(JLabel Encabezado) {
        this.Encabezado = Encabezado;
    }

    public JLabel getLabelDNI() {
        return LabelDNI;
    }

    public void setLabelDNI(JLabel LabelDNI) {
        this.LabelDNI = LabelDNI;
    }

    public JLabel getLabelEDAD() {
        return LabelEDAD;
    }

    public void setLabelEDAD(JLabel LabelEDAD) {
        this.LabelEDAD = LabelEDAD;
    }

    public JLabel getLabelIdCuenta() {
        return LabelIdCuenta;
    }

    public void setLabelIdCuenta(JLabel LabelIdCuenta) {
        this.LabelIdCuenta = LabelIdCuenta;
    }

    public JLabel getLabelIdTienda() {
        return LabelIdTienda;
    }

    public void setLabelIdTienda(JLabel LabelIdTienda) {
        this.LabelIdTienda = LabelIdTienda;
    }

    public JLabel getLabelLocalizacion() {
        return LabelLocalizacion;
    }

    public void setLabelLocalizacion(JLabel LabelLocalizacion) {
        this.LabelLocalizacion = LabelLocalizacion;
    }

    public JLabel getLabelNombre() {
        return LabelNombre;
    }

    public void setLabelNombre(JLabel LabelNombre) {
        this.LabelNombre = LabelNombre;
    }

    public JLabel getLabelNombreTienda() {
        return LabelNombreTienda;
    }

    public void setLabelNombreTienda(JLabel LabelNombreTienda) {
        this.LabelNombreTienda = LabelNombreTienda;
    }

    public JLabel getLabelSaldo() {
        return LabelSaldo;
    }

    public void setLabelSaldo(JLabel LabelSaldo) {
        this.LabelSaldo = LabelSaldo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteFranquiciado_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteFranquiciado_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteFranquiciado_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteFranquiciado_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteFranquiciado_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizaLista;
    private javax.swing.JButton BotonAñadirProducto;
    private javax.swing.JButton BotonComprar;
    private javax.swing.JButton BotonEliminarProducto;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JLabel Encabezado;
    private javax.swing.JLabel LabelDNI;
    private javax.swing.JLabel LabelEDAD;
    private javax.swing.JLabel LabelIdCuenta;
    private javax.swing.JLabel LabelIdTienda;
    private javax.swing.JLabel LabelLocalizacion;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelNombreTienda;
    private javax.swing.JLabel LabelSaldo;
    private javax.swing.JTextField TextoNombreProducto;
    private javax.swing.JTextField TextoPrecioProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
