/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package is2trabajopatrones.GUI;

import is2trabajopatrones.IS2TrabajoPatrones;
import TiendaProducto.Producto;
import TiendaProducto.Tienda;
import javax.swing.JOptionPane;

/**
 *
 * @author Equipo
 */
public class InicioSesion_GUI extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion_GUI
     */
    public InicioSesion_GUI() {
        initComponents();
        TextoPin.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        TextoDNI = new javax.swing.JTextField();
        TextoPin = new javax.swing.JTextField();
        RadioBotonClienteNormal = new javax.swing.JRadioButton();
        RadioBotonClienteSocio = new javax.swing.JRadioButton();
        RadioBotonClienteFranquiciado = new javax.swing.JRadioButton();
        BotonVolver = new javax.swing.JButton();
        BotonInicioSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Inicio de Sesion");

        jLabel2.setText("Por favor, complete los siguientes campos:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("DNI:");

        jLabel5.setText("ID tienda:");

        jLabel6.setText("(Solo clientes franquiciados)");

        buttonGroup1.add(RadioBotonClienteNormal);
        RadioBotonClienteNormal.setText("Cliente Normal");
        RadioBotonClienteNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBotonClienteNormalActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioBotonClienteSocio);
        RadioBotonClienteSocio.setText("Cliente Socio");
        RadioBotonClienteSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBotonClienteSocioActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioBotonClienteFranquiciado);
        RadioBotonClienteFranquiciado.setText("Cliente Franquiciado");
        RadioBotonClienteFranquiciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBotonClienteFranquiciadoActionPerformed(evt);
            }
        });

        BotonVolver.setText("Volver");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        BotonInicioSesion.setText("Iniciar Sesion");
        BotonInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TextoPin)
                                            .addComponent(TextoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextoDNI, javax.swing.GroupLayout.Alignment.LEADING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RadioBotonClienteNormal)
                                    .addComponent(RadioBotonClienteSocio)
                                    .addComponent(RadioBotonClienteFranquiciado))
                                .addGap(35, 35, 35))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioBotonClienteNormal))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioBotonClienteSocio))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextoPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioBotonClienteFranquiciado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonVolver)
                    .addComponent(BotonInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        IS2TrabajoPatrones.pantIni.setVisible(true);
        IS2TrabajoPatrones.pantIni.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void BotonInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioSesionActionPerformed
        if(RadioBotonClienteNormal.isSelected()){
            IS2TrabajoPatrones.sesionActual = IS2TrabajoPatrones.trabajo.InicioSesion(TextoNombre.getText(), TextoDNI.getText());
            if(IS2TrabajoPatrones.sesionActual!=null){
                IS2TrabajoPatrones.clNorm.setVisible(true);
                IS2TrabajoPatrones.clNorm.setLocationRelativeTo(null);
                
                IS2TrabajoPatrones.clNorm.getEncabezado().setText("Bienvenido "+ IS2TrabajoPatrones.sesionActual.getNombre());
                IS2TrabajoPatrones.clNorm.getLabelNombre().setText(IS2TrabajoPatrones.sesionActual.getNombre());
                IS2TrabajoPatrones.clNorm.getLabelDNI().setText(IS2TrabajoPatrones.sesionActual.getId());
                IS2TrabajoPatrones.clNorm.getLabelEDAD().setText(""+IS2TrabajoPatrones.sesionActual.getEdad());
                IS2TrabajoPatrones.clNorm.getLabelIdBanco().setText(IS2TrabajoPatrones.sesionActual.getCuentabancaria().getId());
                IS2TrabajoPatrones.clNorm.getLabelSaldo().setText(""+IS2TrabajoPatrones.sesionActual.getCuentabancaria().getBalance());
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(this, "ERROR: El cliente no existe o datos erroneos\n");                
            }
        }else if(RadioBotonClienteSocio.isSelected()){
            IS2TrabajoPatrones.sesionActual = IS2TrabajoPatrones.trabajo.InicioSesion(TextoNombre.getText(), TextoDNI.getText());
            if(IS2TrabajoPatrones.sesionActual!=null){
                IS2TrabajoPatrones.clSoc.setVisible(true);
                IS2TrabajoPatrones.clSoc.setLocationRelativeTo(null);
                
                IS2TrabajoPatrones.clSoc.getEncabezado().setText("Bienvenido "+ IS2TrabajoPatrones.sesionActual.getNombre());
                IS2TrabajoPatrones.clSoc.getLabelNombre().setText(IS2TrabajoPatrones.sesionActual.getNombre());
                IS2TrabajoPatrones.clSoc.getLabelDNI().setText(IS2TrabajoPatrones.sesionActual.getId());
                IS2TrabajoPatrones.clSoc.getLabelEDAD().setText(""+IS2TrabajoPatrones.sesionActual.getEdad());
                IS2TrabajoPatrones.clSoc.getLabelIdBanco().setText(IS2TrabajoPatrones.sesionActual.getCuentabancaria().getId());
                IS2TrabajoPatrones.clSoc.getLabelSaldo().setText(""+IS2TrabajoPatrones.sesionActual.getCuentabancaria().getBalance());
                        
                this.setVisible(false);
                
            }else{
                JOptionPane.showMessageDialog(this, "ERROR: El cliente no existe o datos erroneos\n");
            }
            
        }else{
            IS2TrabajoPatrones.sesionActual = IS2TrabajoPatrones.trabajo.InicioSesionFranquiciado(TextoNombre.getText(), TextoDNI.getText(), TextoPin.getText());
            if(IS2TrabajoPatrones.sesionActual!=null){
                IS2TrabajoPatrones.clFranq.setVisible(true);
                IS2TrabajoPatrones.clFranq.setLocationRelativeTo(null);
                
                Tienda t = IS2TrabajoPatrones.trabajo.BuscarTienda(TextoPin.getText());
                
                IS2TrabajoPatrones.clFranq.getEncabezado().setText("Bienvenido "+ IS2TrabajoPatrones.sesionActual.getNombre());
                IS2TrabajoPatrones.clFranq.getLabelNombre().setText(IS2TrabajoPatrones.sesionActual.getNombre());
                IS2TrabajoPatrones.clFranq.getLabelDNI().setText(IS2TrabajoPatrones.sesionActual.getId());
                IS2TrabajoPatrones.clFranq.getLabelEDAD().setText(""+IS2TrabajoPatrones.sesionActual.getEdad());
                IS2TrabajoPatrones.clFranq.getLabelIdCuenta().setText(IS2TrabajoPatrones.sesionActual.getCuentabancaria().getId());
                IS2TrabajoPatrones.clFranq.getLabelSaldo().setText(""+IS2TrabajoPatrones.sesionActual.getCuentabancaria().getBalance());
                IS2TrabajoPatrones.clFranq.getLabelNombreTienda().setText(t.getNombre());
                IS2TrabajoPatrones.clFranq.getLabelLocalizacion().setText(t.getLocalizacion());
                IS2TrabajoPatrones.clFranq.getLabelIdTienda().setText(t.getIdTienda());
                for(Producto p:t.getLdp()){
                    IS2TrabajoPatrones.clFranq.productos.addElement(p);
                }
                
                this.setVisible(false);
                
                
            }else{
                JOptionPane.showMessageDialog(this, "ERROR: El cliente no existe o datos erroneos\n");
            }
        }
    }//GEN-LAST:event_BotonInicioSesionActionPerformed

    private void RadioBotonClienteFranquiciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBotonClienteFranquiciadoActionPerformed
        TextoPin.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
    }//GEN-LAST:event_RadioBotonClienteFranquiciadoActionPerformed

    private void RadioBotonClienteNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBotonClienteNormalActionPerformed
        TextoPin.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
    }//GEN-LAST:event_RadioBotonClienteNormalActionPerformed

    private void RadioBotonClienteSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBotonClienteSocioActionPerformed
        TextoPin.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
    }//GEN-LAST:event_RadioBotonClienteSocioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicioSesion;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JRadioButton RadioBotonClienteFranquiciado;
    private javax.swing.JRadioButton RadioBotonClienteNormal;
    private javax.swing.JRadioButton RadioBotonClienteSocio;
    private javax.swing.JTextField TextoDNI;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoPin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
