/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package is2trabajopatrones.GUI;

import EstrategiaClientes.Cliente;
import is2trabajopatrones.IS2TrabajoPatrones;
import TiendaProducto.Producto;
import TiendaProducto.Tienda;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Equipo
 */
public class SesionAdministrador_GUI extends javax.swing.JFrame {

    /**
     * Creates new form SesionAdministrador_GUI
     */
    DefaultListModel clientes = new DefaultListModel();
    DefaultListModel tiendas = new DefaultListModel();
    DefaultListModel productos = new DefaultListModel();
    public SesionAdministrador_GUI() {
        initComponents();
        jList1.setModel(clientes);
        jList2.setModel(tiendas);
        jList3.setModel(productos);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        BotonVolver = new javax.swing.JButton();
        BotonCliente = new javax.swing.JButton();
        BotonTienda = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        BotonProducto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BotonInciarBaseDeDatos = new javax.swing.JButton();
        LabelEDAD = new javax.swing.JLabel();
        LabelIdCuenta = new javax.swing.JLabel();
        LabelSaldo = new javax.swing.JLabel();
        LabelClienteTienda = new javax.swing.JLabel();
        LabelLocalizacion = new javax.swing.JLabel();
        LabelIdTienda = new javax.swing.JLabel();
        LabelNombreProducto = new javax.swing.JLabel();
        LabelPrecioProducto = new javax.swing.JLabel();
        BotonActualizarDatos = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        LabelSaldoMultinacional = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("SESION ADMINISTRADOR");

        jLabel2.setText("Lista de clientes:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel3.setText("Lista de tiendas:");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        BotonVolver.setText("Cerrar sesion");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        BotonCliente.setText("Seleccionar cliente");
        BotonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonClienteActionPerformed(evt);
            }
        });

        BotonTienda.setText("Seleccionar tienda");
        BotonTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTiendaActionPerformed(evt);
            }
        });

        jLabel4.setText("Productos de tienda:");

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        BotonProducto.setText("Seleccionar producto");
        BotonProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonProductoActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre:");

        jLabel6.setText("Precio:");

        jLabel7.setText("Cliente:");

        jLabel8.setText("Localizacion:");

        jLabel9.setText("ID de tienda:");

        jLabel10.setText("Edad:");

        jLabel11.setText("DNI:");

        jLabel12.setText("SALDO:");

        BotonInciarBaseDeDatos.setText("Iniciar base de datos de prueba");
        BotonInciarBaseDeDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInciarBaseDeDatosActionPerformed(evt);
            }
        });

        LabelEDAD.setText("---");

        LabelIdCuenta.setText("---");

        LabelSaldo.setText("---");

        LabelClienteTienda.setText("---");

        LabelLocalizacion.setText("---");

        LabelIdTienda.setText("---");

        LabelNombreProducto.setText("---");

        LabelPrecioProducto.setText("---");

        BotonActualizarDatos.setText("Actualizar datos");
        BotonActualizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarDatosActionPerformed(evt);
            }
        });

        jLabel13.setText("Saldo Multinacional:");

        LabelSaldoMultinacional.setText("jLabel14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotonVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelSaldo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelIdCuenta))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelEDAD))
                            .addComponent(BotonCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonActualizarDatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(BotonInciarBaseDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelIdTienda))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonTienda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelClienteTienda))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelLocalizacion)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LabelNombreProducto))
                                    .addComponent(jScrollPane3)
                                    .addComponent(BotonProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LabelPrecioProducto)))))))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(LabelSaldoMultinacional)
                .addGap(0, 100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13)
                    .addComponent(LabelSaldoMultinacional))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonCliente)
                            .addComponent(BotonTienda)
                            .addComponent(BotonProducto))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(LabelEDAD)
                            .addComponent(LabelClienteTienda)
                            .addComponent(LabelNombreProducto))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(LabelLocalizacion)
                            .addComponent(LabelPrecioProducto)))
                    .addComponent(LabelIdCuenta, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LabelIdTienda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonVolver)
                            .addComponent(BotonInciarBaseDeDatos)
                            .addComponent(BotonActualizarDatos))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(LabelSaldo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonClienteActionPerformed
        int index= jList1.getSelectedIndex();
        Cliente cliente=(Cliente)clientes.getElementAt(index);
        LabelEDAD.setText(""+cliente.getEdad());
        LabelIdCuenta.setText(cliente.getId());
        LabelSaldo.setText(""+cliente.getCuentabancaria().getBalance());
    }//GEN-LAST:event_BotonClienteActionPerformed

    private void BotonTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTiendaActionPerformed
        int index= jList2.getSelectedIndex();
        Tienda tienda=(Tienda)tiendas.getElementAt(index);
        productos.removeAllElements();
        for(Producto p:tienda.getLdp()){
            productos.addElement(p);
        }
        LabelClienteTienda.setText(tienda.getCliente().getNombre());
        LabelLocalizacion.setText(tienda.getLocalizacion());
        LabelIdTienda.setText(tienda.getIdTienda());
    }//GEN-LAST:event_BotonTiendaActionPerformed

    private void BotonProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProductoActionPerformed
        int index= jList3.getSelectedIndex();
        Producto producto=(Producto)productos.getElementAt(index);
        LabelNombreProducto.setText(producto.getNombre());
        LabelPrecioProducto.setText(""+producto.getPrecio());
    }//GEN-LAST:event_BotonProductoActionPerformed

    public JLabel getLabelSaldoMultinacional() {
        return LabelSaldoMultinacional;
    }

    public void setLabelSaldoMultinacional(JLabel LabelSaldoMultinacional) {
        this.LabelSaldoMultinacional = LabelSaldoMultinacional;
    }

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        IS2TrabajoPatrones.pantIni.setVisible(true);
        IS2TrabajoPatrones.pantIni.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void BotonInciarBaseDeDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInciarBaseDeDatosActionPerformed
        JOptionPane.showMessageDialog(this, "Base de datos de prueba instalada\n");
        IS2TrabajoPatrones.trabajo.creaClienteNormal("49135819E", "Pedro", 19, "0000", 1000);
        IS2TrabajoPatrones.trabajo.creaClienteNormal("11111111A", "Juan", 22, "0001", 1500);
        IS2TrabajoPatrones.trabajo.creaClienteNormal("22222222B", "Paula", 21, "0002", 1900);
        IS2TrabajoPatrones.trabajo.creaClienteSocio("33333333C", "Luis", 26, "0003", 900);
        IS2TrabajoPatrones.trabajo.creaClienteSocio("44444444D", "Antonio", 25, "0004", 2000);
        IS2TrabajoPatrones.trabajo.creaClienteSocio("55555555E", "Andres", 31, "0005", 3000);
        IS2TrabajoPatrones.trabajo.creaClienteFranquiciado("66666666F", "Araceli", 49, "0006", 4000, "000", "Simplificando", "Utrera");
        IS2TrabajoPatrones.trabajo.creaClienteFranquiciado("77777777G", "Jose", 29, "0007", 2000, "001", "CablesSL", "Montequinto");
        IS2TrabajoPatrones.trabajo.creaClienteFranquiciado("88888888H", "Paco", 59, "0008", 50000, "002", "Mathfast", "Sevilla");
        Tienda t1 = IS2TrabajoPatrones.trabajo.BuscarTienda("000");
        Tienda t2 = IS2TrabajoPatrones.trabajo.BuscarTienda("001");
        Tienda t3 = IS2TrabajoPatrones.trabajo.BuscarTienda("002");
        IS2TrabajoPatrones.ProductosElectronicos(t1.getLdp());
        IS2TrabajoPatrones.ProductosElectronicos(t2.getLdp());
        IS2TrabajoPatrones.ProductosElectronicos(t3.getLdp());
    }//GEN-LAST:event_BotonInciarBaseDeDatosActionPerformed

    private void BotonActualizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarDatosActionPerformed
        IS2TrabajoPatrones.sesAdm.clientes.removeAllElements();
        for(Cliente c:IS2TrabajoPatrones.trabajo.getListaDeClientes()){
            IS2TrabajoPatrones.sesAdm.clientes.addElement(c);
        }
        
        IS2TrabajoPatrones.sesAdm.tiendas.removeAllElements();
        for(Tienda t:IS2TrabajoPatrones.trabajo.getListaDeTiendas()){
            IS2TrabajoPatrones.sesAdm.tiendas.addElement(t);
        }
        
        productos.removeAllElements();
        LabelEDAD.setText("---");
        LabelIdCuenta.setText("---");
        LabelSaldo.setText("---");
        LabelClienteTienda.setText("---");
        LabelLocalizacion.setText("---");
        LabelIdTienda.setText("---");
        LabelNombreProducto.setText("---");
        LabelPrecioProducto.setText("---");
    }//GEN-LAST:event_BotonActualizarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SesionAdministrador_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SesionAdministrador_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SesionAdministrador_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SesionAdministrador_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SesionAdministrador_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizarDatos;
    private javax.swing.JButton BotonCliente;
    private javax.swing.JButton BotonInciarBaseDeDatos;
    private javax.swing.JButton BotonProducto;
    private javax.swing.JButton BotonTienda;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JLabel LabelClienteTienda;
    private javax.swing.JLabel LabelEDAD;
    private javax.swing.JLabel LabelIdCuenta;
    private javax.swing.JLabel LabelIdTienda;
    private javax.swing.JLabel LabelLocalizacion;
    private javax.swing.JLabel LabelNombreProducto;
    private javax.swing.JLabel LabelPrecioProducto;
    private javax.swing.JLabel LabelSaldo;
    private javax.swing.JLabel LabelSaldoMultinacional;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
